version: '3'
services:
  backend:
    build: .  # Esto apunta a la carpeta actual, que es news-backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/newsDB
    depends_on:
      - mongo
    networks:
      - news-network

  frontend:
    build: ../news-front  # Esto apunta a la carpeta del frontend
    ports:
      - '3001:80'
    environment:
      - REACT_APP_API_NEWS=http://backend:3000
    networks:
      - news-network
    depends_on:
      - backend
    volumes:
      - ../news-front:/app  # Sincronizar la carpeta del frontend con el contenedor
      - /app/node_modules  # Para evitar problemas con node_modules

  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - news-network

volumes:
  mongo-data:

networks:
  news-network:
    driver: bridge
