version: '3'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/newsDB
    depends_on:
      - mongo
    networks:
      - news-network

  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - news-network

volumes:
  mongo-data:

networks:
  news-network:
    driver: bridge
